import json
from learning.lesson_support import enrich
from learning.external_support import enrich_external
from pathlib import Path
ROOT=Path(__file__).parent
paths={
'story':dict(name='Story Makers',ages='Suggested ages 6–7',time='10–15 min',summary='Make characters move, talk and tell your own stories. Picture blocks; no other app needed.',avatar=11),
'game':dict(name='Game Makers',ages='Suggested ages 8–10',time='20–30 min',summary='Build games with scores, choices and challenges. Start here, then explore Scratch.',avatar=17),
'dev':dict(name='Game Developers',ages='Suggested ages 11+ · or ready for typed code',time='30–45 min',summary='Practice code, build in Godot and play your game on a computer or Retroid.',avatar=18)}
# Each row: title | concept explanation | three concrete steps | recall | hint | stretch.
story='''Meet your companion|A command tells your character what to do. Run follows your commands.|Pick a character;Add Move right with a value of 1;Press Run and watch|What changed when you pressed Run?|Press a command in the toolbox to add it.|Try another theme without changing your commands.
A bigger step|A number changes how far the same command moves a character.|Change Move right to 2;Run again;Try 4 and compare|Which number moved farther?|The number box inside a block is editable.|Find a number that stops near the middle.
First, then next|A sequence runs in order, from top to bottom.|Add Move right 2;Add Say Hello;Run and describe the order|What happens first?|Use the up and down buttons to change block order.|Make a three-command sequence.
Up and down|Characters have a position. Up and down change one part of it.|Add Move up 1;Add Move down 2;Run and find the finishing spot|Did the character finish higher or lower?|One down step cancels one up step.|Return to the starting height.
Change the order|The same commands can tell a different story in a new order.|Add Say Ready;Add Move right 2;Swap the blocks and run both versions|How did the order change the story?|Use the block's earlier/later controls.|Make a surprise ending.
Take a breath|Wait pauses a sequence before the next action.|Add Say Hello;Add Wait 1;Add Say Goodbye and run|Where did the pause happen?|Wait uses seconds, not movement steps.|Use two pauses in a conversation.
Show what you know|You can create a sequence without copying someone else's.|Clear only the practice program;Make move, say and wait actions;Explain it to a grown-up|Which command would you change first?|A tiny finished story is enough.|Let someone predict your program.
Do it again|Repeat performs the same movement several times.|Add Repeat right 1 with count 3;Run;Compare with three Move right 1 blocks|What does the repeat count mean?|Repeat has a direction, step size and count.|Try a count of 4.
Count the repeats|Changing a loop count changes how many times it acts.|Make Repeat up 1 count 2;Predict where it stops;Change count to 3 and run|Did your prediction match?|Count the repetitions on your fingers.|Return down using another repeat.
Say it your way|Speech gives a character personality; your words are part of the program.|Add a short greeting in Say;Run and read it;Change the greeting to fit your theme|What stayed the same when words changed?|Short phrases fit on the stage.|Tell a joke in two speech blocks.
Two companions|A program can choose which character receives its actions.|Select Companion 2 in a block;Make it say Hello;Make Companion 1 answer|Which character did each block control?|The companion number is on each block.|Move both characters to meet.
When I tap|An event starts a program when something happens.|Change the trigger to Tap character;Run to get ready;Tap your character to start the sequence|What started your commands?|Run prepares tap-triggered programs; then tap the stage character.|Give the character a surprise greeting.
A little tune|Sound can give feedback when an action happens.|Add Sound;Put it after a greeting;Run, then try the sound-off switch|Can the story work without sound?|A tap or Run unlocks sound on most browsers.|Pair a tune with a movement.
Fix the mix-up|Debugging means finding why the result differs from your plan.|Make Say Goodbye before Hello;Run and notice the mix-up;Reorder the blocks and run again|What did you fix?|Change one thing at a time.|Ask a sibling to mix up two blocks.
A new scene|A scene is a new part of your story. You can create two scenes.|Choose Scene 2 and a background theme;Give it a greeting;Return to Scene 1|How are the scenes different?|Each scene has its own program and starting layout.|Use a different companion in Scene 2.
Go to the next scene|A scene-change command moves the story to another page.|In Scene 1 add a short greeting;Add Next scene;Run and watch Scene 2 begin|Which command changed scenes?|Next scene starts the other scene's Start program.|Add a goodbye before changing.
Send a message|A message lets one scene start the other scene's sequence.|Choose Message as Scene 2's trigger;In Scene 1 add Send message;Run and watch Scene 2 respond|What made the other scene start?|Send message uses the Message trigger in the other scene.|Make a call-and-response story.
Hide and reveal|Showing and hiding a character can create a surprise.|Add Hide for Companion 2;Wait 1;Add Show for Companion 2|What was hidden during the wait?|Hidden characters still have their own position.|Add a greeting after the reveal.
Choose a beginning|A story needs a clear way to start.|Use a Start trigger in Scene 1;Write a welcome line;Test from Reset and Run|Would a friend know how to begin?|The stage title and Run button help the player.|Try a Tap character beginning instead.
Choose your story|A small plan helps you finish something that is your own.|Pick characters and a setting;Write or say a beginning and ending;Build the first three actions|What is your story about?|Choose one idea you can finish.|Use two scenes if you want.
Build the beginning|The first scene introduces the character and goal.|Open your saved project;Add a greeting and movement;Run and revise one action|What does your character want?|You can keep the program short.|Make Companion 2 reply.
Build the middle|The middle shows something happening or changing.|Add a repeat or wait;Add a second character action;Test the sequence order|What changes in the middle?|A pause can make a moment clearer.|Include a reveal.
Build the ending|An ending tells the player that the story is finished.|Add a final speech line;Move to Scene 2 if needed;Run the whole story|How will the player know it ended?|Say The end is a good first ending.|Invent your own ending phrase.
Make it tappable|A tap event lets the player take part.|Choose Tap character for a scene;Write its response;Reset, Run and test the tap|What does the player do?|Tell your player which character to tap.|Make the tap reveal Companion 2.
Make it readable|Clear words and actions help someone understand your creation.|Shorten a long speech line;Put waits between speech;Check with sound turned off|What helped you understand the story?|Say one thing at a time.|Choose two contrasting character colors.
Catch-up and play|Rest and revision are part of learning. Choose one unfinished task.|Open a favorite lesson;Finish one small change;Play your project for fun|What would you like to improve?|You do not have to add a new feature today.|Try an optional earlier challenge.
Test with a friend|A playtest reveals what a new player finds confusing.|Ask someone to press Run;Watch without explaining;Fix one confusing part|Where did your player need help?|Observe before changing the program.|Ask what they liked best.
Fix one thing|Small fixes can make a story easier to enjoy.|Choose one issue from yesterday;Change just that part;Run the entire story again|Did the fix help?|Save a backup before a large change.|Explain the fix in your own words.
Save your creation|A saved project lets you return and make another version.|Give your project a title;Save or download its project file;Reset and replay to verify it|Where will you find your creation later?|Guests can keep a local draft on their own device or download it.|Keep a second themed version.
Creator showcase|You can explain and improve a program you made.|Show your two-scene story;Explain an event and a repeat;Change one command without a recipe|Which part did you make yourself?|A short story you understand is a success.|Plan a new story for November.'''
game='''Meet the game lab|Games follow rules written as commands.|Choose a theme and character;Add Move right 2;Run and predict the result|What rule did you create?|The browser lab is a small teaching tool.|Change a rule and compare.
Positions on the stage|Position is described by horizontal and vertical movement.|Move right 2 and up 1;Run;Change one distance|Which command changes height?|Up and down change the vertical position.|Return to your starting position.
Events start actions|An event is a reason for a program to run.|Try the Start trigger;Try Tap character;Explain the difference|What started each version?|Run arms a tap-triggered program.|Create a welcome after a tap.
Variables remember|A variable stores a value that can change.|Set the target to 3;Use exactly three treasures on the stage;Run and check the score display|What does score remember?|Tap the stage in Layout mode to place treasures.|Compare targets 3 and 5.
Collect a treasure|Contact with a treasure can increase the score.|Place one treasure near the player;Add movement toward it;Run and observe the score|When should the score change?|Collectibles are gathered when the character gets close.|Collect two treasures with one route.
Conditions choose|An if-condition performs an action only when its test is true.|Add If score reached target, say You win;Run with too few treasures;Run again with enough|When did the message appear?|Set a small target while testing.|Write your own win message.
Build without a recipe|A small independent build checks what you understand.|Make a three-treasure route;Add a score condition;Explain your event and variable|What part could you change alone?|Reuse ideas, but choose your own route.|Ask someone to predict the score.
Loops save repetition|A repeat block replaces identical actions.|Build three right steps;Replace them with Repeat right count 3;Compare both versions|Why is a loop useful?|Repeat count means total repetitions.|Use a loop to collect a row.
Tune the speed|A speed value changes how fast movement happens.|Set speed to 2;Run a long movement;Compare with speed 6|Did distance change too?|Speed changes timing, not the number of steps.|Choose a comfortable speed.
Tap controls|A game needs controls its players can use.|Switch the trigger to Controls;Run;Use the on-screen direction buttons|Can you play without a keyboard?|The arrow keys also work in Controls mode.|Test on a tablet in landscape.
A fair obstacle|A hazard introduces a consequence; feedback tells players what happened.|In Layout mode place a hazard;Use Controls and touch it;Move it to a fairer spot|Was the obstacle avoidable?|Reset clears the current play state.|Add a safer route.
An ending and replay|A game should tell players when they win and let them play again.|Set a reachable treasure target;Reach it in Controls mode;Reset and play again|What must reset between rounds?|Score and collected items reset; your layout stays.|Test a losing round too.
Your own small game|Design combines a player, action, goal and challenge.|Name your game;Arrange treasures and a hazard;Write the instructions using Say|What is the goal?|Keep the first game tiny.|Try another theme with the same rules.
Test your rules|Testing includes trying things that should fail.|Try a route that misses a treasure;Try hitting a hazard;Try winning and restarting|What happens in each case?|Write down one issue to fix.|Have someone else test.
Meet Scratch|Scratch lets you build larger projects with sprites and blocks.|Open Scratch Create on a compatible computer;Find stage, sprites and code area;Save a project on the computer|Which part is like our stage?|Use the Scratch guide in Help; no public sharing is required.|Give your sprite a themed name.
Move a Scratch sprite|Events and motion blocks become a playable character.|Add when green flag clicked;Add go to x -150 y 0;Add when right arrow pressed, change x by 10|Which blocks initialize the game?|Start with one direction, then add others.|Add an on-screen button for touch.
Scratch repetition|A forever loop checks rules while a game runs.|Add a forever block under the green flag;Inside use if key right arrow pressed;Inside change x by 4|Why check the key repeatedly?|Keep the if block inside forever.|Add left, up and down.
Scratch treasure|A second sprite can detect contact with the player.|Add a treasure sprite;Under green flag use show and wait until touching Player;Hide it when touched|Which sprite detects contact?|Choose your actual player name in touching.|Make it appear at a random position.
Scratch score|A variable counts the treasures collected.|Create score for all sprites;Set score to 0 at start;Change score by 1 before hiding a touched treasure|Where should score reset?|Avoid adding score repeatedly for one contact.|Show the score on the stage.
Plan the finished game|A one-page plan keeps the game manageable.|Choose a theme;Write player, action, goal and hazard;List only essential features|What could you leave out?|A five-treasure collector is enough.|Draw the layout on paper.
Build the player|Complete the controls before adding more features.|Create the themed player;Add all four directions;Test start position and movement|Can another person move it?|Keep movement code on the player sprite.|Add boundary checks.
Build collectibles|Several treasures make the goal interesting.|Make one reliable treasure;Duplicate it to several positions;Test score once per pickup|Did every treasure count once?|Use show at the start and hide after collection.|Use clones if you already understand them.
Build the hazard|A hazard needs a clear consequence.|Add a hazard sprite;Detect touching the player;Broadcast Lose and set playing to 0 on the Stage|What should losing change?|A separate lose message helps coordinate sprites.|Add one life variable.
Win and restart|Broadcasts can coordinate a complete ending.|On Stage wait until score = 5 then broadcast Win;Show a win backdrop or message;Reset score and show treasures on green flag|What needs to restart?|Test replay, not just the first win.|Add a replay button.
Explain the controls|Good instructions help players start independently.|Write a short instruction screen;Show the target;Ask a sibling to start without help|Were the controls clear?|Use large touch targets if needed.|Add a sound-off option.
Catch-up day|Finishing matters more than adding features.|Pick one missing feature;Complete it;Save a working version|What is essential to finish?|Remove a feature if it prevents finishing.|Play someone else's creation with permission.
Family playtest|Feedback helps you find confusing rules.|Ask two people to play;Watch without coaching;Write two useful observations|What confused your players?|Ask where they got stuck.|Compare computer and tablet controls.
Fix and balance|Make one change and retest before making another.|Fix the biggest issue;Adjust speed or hazard position;Replay win, lose and restart|Did the change improve fairness?|Keep a saved copy before editing.|Test an unexpected input.
Save the source|A project file preserves the editable game.|Use File > Save to your computer;Keep a dated .sb3 copy;Reopen it to check it works|Is a screenshot an editable project?|The project file, not the picture, contains the blocks.|Keep a second theme version.
Game night|A finished game is playable and explainable.|Show your game;Explain a variable, loop and condition;Change one rule independently|What are you proud of learning?|Browser-lab projects count as browser creations; Scratch projects are tracked separately.|Choose your November improvement.'''
dev='''Your first instructions|A program is a precise sequence. Our lab uses teaching commands, not GDScript.|Open the code tab;Run move right 2;Change the number and run again|What did the computer follow?|Open Command reference under the typed editor.|Explain why exact spelling matters.
Variables and values|Values control behavior; real variables give values names.|Change speed 3 to speed 6;Compare the timing;Read the GDScript variable example below|What can you change without rewriting the rule?|Our small lab has speed and target commands.|Predict before running.
Functions are reusable actions|A function gives a reusable action a name.|Make a short move-and-say sequence;Run it twice;Read the function example below and identify the function body|Why put an action in a function?|Indentation groups GDScript statements.|Describe a function in everyday language.
If makes a decision|Conditions decide whether an action should run.|Set target to 1;Add ifwin You win;Run a route with and without a pickup|What is the condition testing?|The lab uses ifwin as a limited teaching command.|Find a real-life if-condition.
Loops repeat work|Loops perform actions several times.|Run repeat 3 right 1;Compare three move commands;Find the loop in the GDScript example below|When would a loop simplify code?|The lab repeat syntax is repeat COUNT DIRECTION STEPS.|Try a different count.
Debug a program|Useful debugging compares expected behavior with actual behavior.|Make a typo in move;Read the line-numbered error;Fix and rerun|What did the error tell you?|This lab rejects unknown commands rather than executing arbitrary code.|Change one thing at a time.
Independent browser challenge|Understanding means predicting, changing and explaining.|Plan a treasure route;Write it in lab commands;Explain one condition and repeat|Which part can you explain without help?|You may use the command reference, but choose your own route.|Run another themed version.
Meet Godot|Nodes do jobs; scenes group nodes into reusable pieces.|Install the current stable Godot 4 standard edition;Create a 2D project using Compatibility;Create a Node2D main scene and save it|What is a scene?|The tool guide includes setup steps and official documentation.|Run an empty main scene.
Player scene|CharacterBody2D provides a useful starting point for controlled movement.|Create a CharacterBody2D player scene;Add Sprite2D or Polygon2D and CollisionShape2D;Save Player.tscn and instance it in Main|Which node holds the collision shape?|Use a simple shape before detailed art.|Label your nodes clearly.
Move and test early|Input actions separate controls from game logic.|Add movement actions in Project Settings > Input Map;Attach the movement script from the tool guide;Run on the computer and test one controller if available|Why use actions instead of a specific key everywhere?|Check script node type and exact action names.|Parent can start Android export setup now.
A pickup area|Area2D signals tell us when another body enters an area.|Create a treasure Area2D with art and CollisionShape2D;Attach the pickup script that connects body_entered;Remove the treasure when the player enters|Why use an area for a pickup?|Check collision layers and masks if it does not fire.|Print a message before adding score.
Score and signals|Signals let objects report events without owning all game logic.|Give the treasure a collected signal;Connect it to Main;Increment score in Main and update a Label|Who owns the score?|The pickup guide shows a minimal signal pattern.|Keep the player separate from the score label.
Reusable scenes|One scene can create many instances of the same object.|Save the treasure scene;Instance five treasures in Main;Test each pickup and score|What changes in every instance when you edit the scene?|Use a scene instance, not five copied scripts.|Give instances different positions.
Checkpoint and backup|A working checkpoint makes experiments safer.|Save the project;Copy the folder or commit it to your own version control;Test one complete pickup route|Could you restore this version?|Do not back up only the exported APK.|Write one problem to solve next.
A hazard|Hazards need detection and a clear consequence.|Create a hazard Area2D;Attach the hazard script that connects body_entered;Tell Main to switch to a losing state|How does the player learn what happened?|Start with a stationary hazard.|Add a brief visual feedback effect.
Game states|Playing, won and lost should allow different actions.|Add a state variable or enum in Main;Stop scoring when not playing;Show distinct win and lose messages|What should be disabled after a loss?|A single owner for state avoids conflicting rules.|Pause the player after an ending.
Timer and victory|A Timer can introduce a time limit without manual counting.|Add a Timer;Connect timeout to the losing state;Stop the timer after collecting the target|Which event ends the round first?|Test with a generous time limit first.|Display remaining time.
Restart and handheld test|Restart must restore all state, objects and controls.|Add a restart input action;Reload the current scene or reset all state;Parent exports an early APK and tests on Retroid|What must reset?|Android setup guide lists tools and export steps.|Record controller button names on the device.
Art and sound|Feedback supports understanding rather than hiding the rules.|Choose a theme palette;Add one pickup sound and a visible score change;Test with sound muted|Can the player still understand the result?|Use properly licensed or original assets.|Add a volume control.
Design your own collector|Scope keeps an original project finishable.|Write player, action, goal and hazard;Draw one small level;List must-have and optional features|What is the smallest complete version?|Keep one level and one main action.|Choose a theme variant.
Build the core|Build the playable action before polish.|Start your own project or adapt your checkpoint;Implement movement and one pickup;Play the core loop|Is it playable yet?|Use what you already understand.|Explain your script without reading it verbatim.
Build the level|A level arranges reusable rules in space.|Place five pickups;Add safe boundaries;Test every area is reachable|Can the player reach every item?|Avoid unreachable corners.|Use an array to organize objects.
Add a fair challenge|Difficulty should come from understandable rules.|Place one hazard;Test a safe route;Tune player speed and hit areas|Does losing feel fair?|Ask a new player before adding more hazards.|Add one moving hazard if time allows.
Finish the round|Win, lose and replay turn a prototype into a game.|Add your win condition;Add your lose condition;Test restart from both endings|Does the second round work?|Many bugs appear only after restart.|Test repeated rapid inputs.
Controller-friendly UI|A handheld game must be usable without a mouse.|Check Input Map controller bindings;Make menu buttons focusable;Test navigating and starting with the controller|Where did you still need a mouse?|Use ui_accept and focus neighbors for buttons.|Add an on-screen control diagram.
Catch-up and scope cut|Removing unfinished extras can save a release.|Choose the biggest missing essential;Fix it;Remove an optional feature that is still broken|What can you finish today?|One polished level is enough.|Make a short bug list.
Playtest on real hardware|Computer success does not guarantee handheld usability.|Run on computer;Run on Retroid with a parent;Record controls, text readability and performance|What changed on the handheld?|Observe a new player without coaching.|Test sound off and pause/resume.
Fix the biggest bugs|Prioritize crashes and broken rules before decoration.|Fix the most serious issue;Retest win, lose and replay;Check another player can start alone|Which fix mattered most?|Keep a known-good backup.|Measure performance if needed.
Release checklist|Source files and exports serve different purposes.|Save and back up the source project;Export a working APK for the Retroid test device;Write controls and known limitations|Which file lets you edit the game later?|The APK plays; the Godot project edits.|Keep a desktop build too.
Developer showcase|Ownership means understanding the game and its code.|Show a finished game;Explain a function, signal and state;Make one independent change and rebuild|What can you build next without AI writing it?|A reference guide is allowed; explain your own decisions.|Plan a November feature.'''
resources={
'story':[dict(label='Using this builder',url='#help-builder')],
'game':[dict(label='Scratch tutorials',url='https://scratch.mit.edu/ideas'),dict(label='Open Scratch editor',url='https://scratch.mit.edu/projects/editor/'),dict(label='Scratch browser requirements',url='https://mitscratch.freshdesk.com/en/support/solutions/articles/4000156845-what-are-the-system-requirements-for-scratch-')],
'dev':[dict(label='Download Godot',url='https://godotengine.org/download/'),dict(label='Godot step by step',url='https://docs.godotengine.org/en/stable/getting_started/step_by_step/index.html'),dict(label='First 2D game',url='https://docs.godotengine.org/en/stable/getting_started/first_2d_game/index.html'),dict(label='Android export',url='https://docs.godotengine.org/en/stable/tutorials/export/exporting_for_android.html'),dict(label='Input examples',url='https://docs.godotengine.org/en/stable/tutorials/inputs/input_examples.html')]}
lessons=[]
for path,source in [('story',story),('game',game),('dev',dev)]:
 for day,row in enumerate(source.splitlines(),1):
  title,explain,steps,recall,hint,stretch=row.split('|')
  mode='browser' if path=='story' or (path=='game' and day<=14) or (path=='dev' and day<=7) else ('scratch' if path=='game' else 'godot')
  starter=[dict(op='right',value=2,target=1),dict(op='say',value='Hello!',target=1)]
  if day in (6,10,13):starter=[dict(op='say',value='Hello!',target=1),dict(op='wait',value=1,target=1),dict(op='say',value='Your turn!',target=2)]
  if day in (8,9):starter=[dict(op='repeat',value=1,count=3,direction='right',target=1)]
  lessons.append(enrich_external(enrich(dict(id=f'{path}-{day}',path=path,day=day,title=title,concept=explain,steps=steps.split(';'),recall=recall,hint=hint,challenge=stretch,mode=mode,starter=starter,resources=resources[path]))))
assert len(lessons)==90
out=dict(month='October',year=2026,paths=paths,lessons=lessons)
(ROOT/'public/curriculum.json').write_text(json.dumps(out,ensure_ascii=False,indent=2))
print('90 lessons generated')
