/* Real Chromium integration checks, disposable local server/accounts only. */
const assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{spawn}=require('node:child_process');
let chromium;try{({chromium}=require('playwright'));}catch{({chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright'));}
const ROOT=path.resolve(__dirname,'..'),OUT=path.join(ROOT,'qa-artifacts');fs.mkdirSync(OUT,{recursive:true});
const dataDir=fs.mkdtempSync(path.join(os.tmpdir(),'pqc-browser-'));const PORT=8098,URL='http://127.0.0.1:'+PORT;
const server=spawn('python3',['server.py','--port',String(PORT)],{cwd:ROOT,env:{...process.env,PQC_DATA_DIR:dataDir,PQC_SECURE_COOKIES:'0',PQC_PARENT_INVITE:'qa-only-setup',PQC_PARENT_SIGNUP:'1',PQC_OPEN_CHILD_SIGNUP:'1'},stdio:['ignore','ignore','pipe']});
const report={environment:'GitHub/local Chromium; simulated tablet viewports, not physical Fire tablets',checks:[],errors:[],screenshots:[]};let browser;
function log(name){report.checks.push(name);console.log('PASS '+name);}
async function screenshot(page,name){const file=name+'.png';await page.screenshot({path:path.join(OUT,file),fullPage:true});report.screenshots.push(file);}
async function click(page,action,value){const sel=`[data-action="${action}"]${value===undefined?'':`[data-value="${value}"]`}`;await page.locator(sel).filter({visible:true}).first().click();}
async function open(page){page.on('dialog',d=>d.accept());page.on('pageerror',e=>report.errors.push(e.message));await page.goto(URL);await page.getByRole('heading',{name:'What would you like to make?'}).waitFor();}
async function quest(page,pathName,day=1){await click(page,'path',pathName);await click(page,'day',day);await page.locator('#stage').waitFor();}
async function noOverflow(page){assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),'Unexpected horizontal overflow');}
async function signOut(page){await click(page,'account');await page.locator('#dialog [data-action="logout"]').click();await page.getByRole('heading',{name:'What would you like to make?'}).waitFor();}
async function login(page,name,secret){await click(page,'account');await page.locator('#login-name').fill(name);await page.locator('#login-secret').fill(secret);await page.locator('#login-form button.primary').click();await page.locator('#dialog').waitFor({state:'hidden'});}
(async()=>{
 for(let i=0;i<80;i++){try{const r=await fetch(URL+'/api/session');if(r.ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
 browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:1440,height:1100},acceptDownloads:true});let page=await context.newPage();await open(page);
 for(const pathName of ['story','game','dev']){
  if(await page.locator('[data-action="choose"]').count())await click(page,'choose');
  await quest(page,pathName);
  for(let day=1;day<=30;day++){
   if(day>1)await click(page,'day',day);
   assert.equal(await page.locator('[data-step]').count(),3);assert.equal(await page.locator('#complete').isEnabled(),false);
   for(const theme of ['royal','space','halloween']){
    await click(page,'theme',theme);
    await page.waitForFunction(()=>Array.from(document.images).every(i=>i.complete&&i.naturalWidth>0));
    assert.equal(await page.evaluate(()=>project().theme),theme);
    assert(await page.locator('#stage').isVisible());
   }
   await noOverflow(page);
  }
  log('30 lessons × 3 themes: '+pathName);
  await click(page,'showcase');await page.getByRole('heading',{name:'You made something of your own.'}).waitFor();await click(page,'day',30);await click(page,'month');await click(page,'choose');
 }
 await quest(page,'story');await click(page,'theme','royal');
 for(let n=0;n<3;n++)await page.locator('#step-'+n).check();await page.locator('#explained').check();assert(await page.locator('#complete').isEnabled());await click(page,'complete');assert.match(await page.locator('#complete').innerText(),/completed/);await page.locator('#quest-note').fill('A disposable QA note');
 log('Task checks, explanation, completion and note');
 await click(page,'clear-program');assert.equal(await page.locator('.block').count(),0);
 const ops=['right','left','up','down','wait','say','repeat','sound','hide','show','next','message','ifwin'];
 for(const op of ops)await click(page,'add-block',op);assert.equal(await page.locator('.block').count(),13);
 await page.locator('.block[data-index="0"] [data-block-field="value"]').fill('3');await page.locator('.block[data-index="5"] [data-block-field="value"]').fill('QA hello');await page.locator('.block[data-index="6"] [data-block-field="count"]').fill('2');await page.locator('.block[data-index="6"] [data-block-field="direction"]').selectOption('up');await page.locator('.block[data-index="5"] [data-block-field="target"]').selectOption('2');
 await page.locator('.block[data-index="0"] [data-action="later"]').click();await page.locator('.block[data-index="1"] [data-action="earlier"]').click();await page.locator('.block[data-index="0"] [data-action="remove-block"]').click();assert.equal(await page.locator('.block').count(),12);log('All 13 blocks, fields, companion selection, reorder and remove');
 await click(page,'clear-program');await click(page,'add-block','right');await page.locator('.block [data-block-field="value"]').fill('6');
 await click(page,'run');await page.waitForFunction(()=>stage.won);assert.match(await page.locator('#score').innerText(),/3 \/ 3/);await screenshot(page,'desktop-royal-win');await click(page,'reset');assert.match(await page.locator('#score').innerText(),/0 \/ 3/);log('Run, movement, treasure collection, winning and reset');
 await click(page,'editor-mode','code');await page.locator('#code').fill('say "Typed result"');await click(page,'run');await page.waitForFunction(()=>stage.runtime.players[0].speech==='Typed result');
 await page.locator('#code').fill('invalid instruction');await click(page,'run');await page.waitForFunction(()=>document.querySelector('#run-status').textContent.includes('Line 1'));
 await page.locator('#code').fill('wait 5\nsay "Should not happen"');await click(page,'run');await click(page,'stop');assert.equal(await page.evaluate(()=>stage.running),false);log('Typed output, line errors and Stop during wait');
 await click(page,'editor-mode','blocks');await click(page,'clear-program');await click(page,'add-block','say');await page.locator('.block [data-block-field="value"]').fill('Tapped hello');await page.locator('#trigger').selectOption('tap');await click(page,'run');const box=await page.locator('#stage').boundingBox();await page.locator('#stage').click({position:{x:110/800*box.width,y:345/450*box.height}});await page.waitForFunction(()=>stage.runtime.players[0].speech==='Tapped hello');log('Tap trigger');
 await page.locator('#trigger').selectOption('controls');await click(page,'clear-program');await click(page,'run');const x=await page.evaluate(()=>stage.runtime.players[0].x);await page.locator('[data-direction="right"]').click();await page.waitForFunction(x=>stage.runtime.players[0].x>x,x);await page.locator('#stage').focus();await page.keyboard.press('ArrowUp');await page.waitForFunction(()=>stage.runtime.players[0].y<345);log('On-screen directions and keyboard');
 await page.locator('summary').filter({hasText:'Arrange the stage'}).click();await page.locator('#layout-tool').selectOption('hazard');await page.locator('#stage').click({position:{x:box.width*.65,y:box.height*.6}});assert.equal(await page.evaluate(()=>project().scenes[0].hazards.length),1);await page.locator('#layout-tool').selectOption('erase');await page.locator('#stage').click({position:{x:box.width*.65,y:box.height*.6}});assert.equal(await page.evaluate(()=>project().scenes[0].hazards.length),0);await page.locator('#layout-tool').selectOption('player2');await page.locator('#stage').click({position:{x:box.width*.5,y:box.height*.5}});await page.locator('#layout-tool').selectOption('');log('Stage placement and erase');
 await page.locator('summary').filter({hasText:'Scene settings'}).click();for(let a=0;a<30;a++)await page.locator('#character-1').selectOption(String(a));await page.locator('#character-2').selectOption('11');await page.locator('#target').fill('5');await page.locator('#target').press('Tab');await page.locator('#speed').fill('8');await page.locator('#speed').press('Tab');await page.locator('#sound').uncheck();assert.equal(await page.evaluate(()=>project().target),5);assert.equal(await page.evaluate(()=>project().sound),false);log('All 30 character options, goal, speed and sound');
 await page.locator('#scene-select').selectOption('1');await click(page,'clear-program');await click(page,'add-block','say');await page.locator('.block [data-block-field="value"]').fill('Scene reply');await page.locator('#trigger').selectOption('message');await page.locator('#scene-select').selectOption('0');await page.locator('#trigger').selectOption('start');await click(page,'clear-program');await click(page,'add-block','message');await click(page,'run');await page.waitForFunction(()=>project().scene===1&&stage.runtime.players[0].speech==='Scene reply');log('Two scenes and message routing');
 await page.locator('#project-title').fill('Disposable QA project');const downloadPromise=page.waitForEvent('download');await click(page,'download');const download=await downloadPromise;const projectPath=path.join(dataDir,'roundtrip.pqc.json');await download.saveAs(projectPath);assert.equal(JSON.parse(fs.readFileSync(projectPath)).title,'Disposable QA project');const chooserPromise=page.waitForEvent('filechooser');await click(page,'import');await (await chooserPromise).setFiles(projectPath);await page.waitForFunction(()=>document.querySelector('#toast').textContent==='Project opened.');log('Project download and import round trip');
 await click(page,'local-settings');for(let a=0;a<30;a++)await page.locator(`#dialog [data-action="profile-avatar"][data-value="${a}"]`).click();await page.locator('#keep-local').check();await click(page,'apply-local');await page.reload();await page.locator('[data-action="day"][data-value="1"]').waitFor();await click(page,'local-settings');await page.locator('#school-mode').check();await click(page,'apply-local');assert.equal(await page.evaluate(()=>localStorage.getItem('pqc-guest')),null);log('All profile avatars, personal persistence and shared-device mode');
 await click(page,'help');await page.getByRole('heading',{name:'A little help, right here'}).waitFor();await click(page,'privacy');await page.getByRole('heading',{name:'Privacy & saving'}).waitFor();await click(page,'close-dialog');await click(page,'parents');await click(page,'parent-register');await page.locator('#register-name').fill('qa-parent');await page.locator('#register-secret').fill('disposable-qa-password');await page.locator('#invite').fill('qa-only-setup');await page.locator('#register-form button.primary').click();await page.getByRole('heading',{name:'Keep your recovery key'}).waitFor();await click(page,'close-dialog');
 await click(page,'new-child');await page.locator('#child-form input[name="secret"]').fill('123456');await page.locator('#child-form select[name="path"]').selectOption('story');await page.locator('#child-form select[name="theme"]').selectOption('royal');await page.locator('#child-form [data-action="child-avatar"][data-value="13"]').click();await page.locator('#child-form button.primary').click();await page.getByRole('heading',{name:'Child account ready'}).waitFor();const childName=await page.locator('#dialog-content b').innerText();await click(page,'close-dialog');await page.locator('.child-row').waitFor();await signOut(page);await login(page,childName,'123456');await click(page,'day',1);await page.locator('#quest-note').fill('Saved online QA');await click(page,'save-now');await page.waitForFunction(()=>document.querySelector('#save-status').textContent==='Saved online');await page.reload();await click(page,'day',1);assert.equal(await page.locator('#quest-note').inputValue(),'Saved online QA');await screenshot(page,'child-saved-progress');log('Parent signup, child creation, child login, online save and reload');
 await signOut(page);
 await click(page,'account');await click(page,'child-register');await page.locator('#register-secret').fill('111111');await page.locator('#register-form button.primary').click();await page.getByRole('heading',{name:'Keep your recovery key'}).waitFor();const orphanName=await page.locator('#dialog-content b').innerText(),orphanKey=await page.locator('#dialog .recovery').innerText();await click(page,'close-dialog');await signOut(page);await click(page,'account');await click(page,'recover');await page.locator('#recover-form [name="username"]').fill(orphanName);await page.locator('#recover-form [name="recoveryKey"]').fill(orphanKey);await page.locator('#recover-form [name="secret"]').fill('222222');await page.locator('#recover-form button.primary').click();await page.getByRole('heading',{name:'Access reset'}).waitFor();await click(page,'close-dialog');await login(page,orphanName,'222222');await click(page,'account');await click(page,'link-parent');await page.locator('#link-form [name="username"]').fill('qa-parent');await page.locator('#link-form [name="secret"]').fill('disposable-qa-password');await page.locator('#link-form button.primary').click();await page.locator('#dialog').waitFor({state:'hidden'});await signOut(page);log('Optional unlinked signup, recovery key reset and parent linking');
 await login(page,'qa-parent','disposable-qa-password');await page.locator('.child-row [data-action="reset-child"]').first().click();await page.locator('#reset-form input').fill('654321');await page.locator('#reset-form button.primary').click();await page.locator('#dialog').waitFor({state:'hidden'});await page.locator('.child-row [data-action="delete-child"]').first().click();await page.waitForFunction(()=>document.querySelectorAll('.child-row').length===1);await page.locator('.child-row [data-action="delete-child"]').click();await page.waitForFunction(()=>!document.querySelector('.child-row'));log('Parent code reset and deletion of disposable child');
 await signOut(page);await click(page,'account');await click(page,'recover');await page.locator('#recover-form').waitFor();await click(page,'close-dialog');await click(page,'local-settings');await click(page,'clear-guest');await page.getByRole('heading',{name:'What would you like to make?'}).waitFor();log('Recovery form and clear guest');
 for(const viewport of [{width:600,height:1024},{width:1024,height:600},{width:800,height:1280},{width:1280,height:800},{width:360,height:740}]){
  const c=await browser.newContext({viewport,hasTouch:true,isMobile:true});const p=await c.newPage();await open(p);await quest(p,'story');await noOverflow(p);if(viewport.width<=700){await click(p,'mobile-view','build');assert(await p.locator('.build-panel').isVisible());await click(p,'editor-mode','code');await p.locator('#code').fill('say "Touch test"');await click(p,'mobile-view','play');assert(await p.locator('#stage').isVisible());await click(p,'run');await p.waitForFunction(()=>stage.runtime.players[0].speech==='Touch test');await click(p,'mobile-view','lesson');assert(await p.locator('.lesson-panel').isVisible());}await screenshot(p,`touch-${viewport.width}x${viewport.height}`);await c.close();
 }
 log('Five touch viewport sizes, portrait/landscape and narrow workspace tabs');
 assert.deepEqual(report.errors,[]);log('No uncaught browser JavaScript errors');
 report.status='passed';
})().catch(e=>{report.status='failed';report.failure=e.stack;console.error(e);process.exitCode=1;}).finally(async()=>{fs.writeFileSync(path.join(OUT,'browser-results.json'),JSON.stringify(report,null,2));if(browser)await browser.close();server.kill();fs.rmSync(dataDir,{recursive:true,force:true});});
