/* Disposable local accounts only. Child signup and linking through actual UI. */
const assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{spawn}=require('node:child_process');
let chromium;try{({chromium}=require('playwright'));}catch{({chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright'));}
const root=path.resolve(__dirname,'..'),out=path.join(root,'qa-artifacts'),data=fs.mkdtempSync(path.join(os.tmpdir(),'pqc-link-')),url='http://127.0.0.1:8096';fs.mkdirSync(out,{recursive:true});
const proc=spawn('python3',['server.py','--port','8096'],{cwd:root,env:{...process.env,PQC_DATA_DIR:data,PQC_PUBLIC_DIR:path.join(root,'dist'),PQC_PARENT_SIGNUP:'1',PQC_PARENT_INVITE:'qa-link-only',PQC_OPEN_CHILD_SIGNUP:'1',PQC_SECURE_COOKIES:'0'},stdio:'ignore'});
const report={checks:[],errors:[],environment:'Disposable Chromium instances; tablet viewport simulations, not physical Fire devices'};let browser;
async function api(context,endpoint,body){const r=body===undefined?await context.request.get(url+'/api/'+endpoint):await context.request.post(url+'/api/'+endpoint,{data:body});assert(r.ok(),await r.text());return r.json();}
async function click(page,action){await page.locator(`[data-action="${action}"]`).filter({visible:true}).first().click();}
async function ready(page){page.on('pageerror',e=>report.errors.push(e.message));await page.goto(url);await page.locator('main h1').waitFor();}
async function shot(page,name){await page.screenshot({path:path.join(out,name+'.png'),fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),'Horizontal overflow');}
async function request(parentPage,username,code){await click(parentPage,'parent-link-child');await parentPage.locator('#parent-link-form [name="username"]').fill(username);await parentPage.locator('#parent-link-form [name="code"]').fill(code);await parentPage.locator('#parent-link-form button.primary').click();await parentPage.getByRole('heading',{name:'Waiting for your child',exact:true}).waitFor();await click(parentPage,'close-dialog');}
(async()=>{
 for(let i=0;i<80;i++){try{if((await fetch(url+'/api/session')).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
 browser=await chromium.launch();const parent=await browser.newContext(),child=await browser.newContext({viewport:{width:600,height:1024}}),other=await browser.newContext();
 await api(parent,'register',{role:'parent',username:'qa-link-parent',secret:'disposable-parent-password',invite:'qa-link-only'});
 await api(other,'register',{role:'parent',username:'qa-link-other',secret:'disposable-parent-password',invite:'qa-link-only'});
 const cp=await child.newPage();await ready(cp);await cp.locator('[data-action="path"][data-value="game"]').click();await cp.locator('[data-action="day"][data-value="1"]').first().click();await cp.getByRole('tab',{name:'Quest',exact:true}).click();
 for(let n=0;n<3;n++)await cp.locator('#step-'+n).check();await cp.locator('#explained').check();await cp.locator('#complete').click();await cp.locator('#quest-note').fill('Guest work before signup');
 await click(cp,'account');await click(cp,'child-register');await cp.locator('[data-action="signup-avatar"][data-value="7"]').click();await cp.locator('#register-form [name="path"]').selectOption('game');await cp.locator('#register-form [name="theme"]').selectOption('space');
 await cp.locator('#register-secret').fill('123456');await cp.locator('#register-form [name="confirmSecret"]').fill('654321');await cp.locator('#register-form button.primary').click();await cp.getByText('Your six-digit codes do not match. Try both again.',{exact:true}).waitFor();
 await shot(cp,'child-signup-portrait');await cp.setViewportSize({width:1024,height:600});await shot(cp,'child-signup-landscape');await cp.setViewportSize({width:600,height:1024});await cp.locator('#register-form [name="confirmSecret"]').fill('123456');await cp.locator('#register-form button.primary').click();await cp.getByRole('heading',{name:'Keep your recovery key',exact:true}).waitFor();
 const username=await cp.locator('#dialog-content b').innerText();const registered=(await api(child,'session')).user;assert.equal(registered.avatar,7);assert.equal(registered.path,'game');assert.equal(registered.theme,'space');assert.equal(registered.parent_id,null);
 const saved=await api(child,'save');assert.equal(saved.payload.completed['game-1'],true);assert.equal(saved.payload.notes['game-1'],'Guest work before signup');
 report.checks.push('Child avatar/path/world selection, mismatched PIN correction and preserved guest work');
 await click(cp,'link-parent');assert.equal(await cp.locator('#dialog input[type="password"]').count(),0);await click(cp,'make-link-code');let code=await cp.locator('#link-code').innerText();await shot(cp,'child-link-code');
 const pp=await parent.newPage();await ready(pp);await request(pp,username,code);assert.equal(await pp.locator('.family-card').count(),0);
 await click(cp,'link-parent');await cp.getByRole('heading',{name:'Confirm your grown-up',exact:true}).waitFor();await cp.getByText('qa-link-parent',{exact:true}).waitFor();await shot(cp,'child-link-confirmation');await click(cp,'decline-link');assert.equal((await api(child,'session')).user.parent_id,null);
 await click(cp,'account');await click(cp,'link-parent');await click(cp,'make-link-code');code=await cp.locator('#link-code').innerText();await request(pp,username,code);await click(cp,'link-parent');await click(cp,'confirm-link');await cp.locator('#dialog').waitFor({state:'hidden'});assert((await api(child,'session')).user.parent_id);
 await click(pp,'refresh-family');await pp.locator('.family-card').waitFor();assert.match(await pp.locator('.family-card').innerText(),/1 of 30 quests completed/);await shot(pp,'linked-existing-child-dashboard');
 assert.equal((await api(child,'save')).payload.notes['game-1'],'Guest work before signup');assert.equal((await api(other,'children')).children.length,0);
 report.checks.push('Parent request, child decline/accept, dashboard progress and other-family isolation');
 await click(pp,'family-code');const familyCode=await pp.locator('#family-code').innerText();await shot(pp,'parent-family-code');
 const sibling=await browser.newContext({viewport:{width:360,height:740}}),sp=await sibling.newPage();await ready(sp);await click(sp,'signup-start');await sp.locator('#register-secret').fill('111111');await sp.locator('#register-form [name="confirmSecret"]').fill('111111');await sp.locator('#register-form [name="familyCode"]').fill(familyCode);await shot(sp,'child-family-signup-narrow');await sp.locator('#register-form button.primary').click();await sp.getByRole('heading',{name:'Keep your recovery key',exact:true}).waitFor();assert.equal((await api(sibling,'session')).user.parent_id,registered.parent_id||(await api(parent,'session')).user.id);
 await click(pp,'revoke-family-code');assert.equal((await api(parent,'children')).children.length,2);report.checks.push('Family-code signup shortcut, revocation and narrow layout');
 await cp.reload();await cp.locator('[data-action="day"][data-value="1"]').first().click();await cp.getByRole('tab',{name:'Quest',exact:true}).click();assert.equal(await cp.locator('#quest-note').inputValue(),'Guest work before signup');report.checks.push('Linked account reload preserves guest lesson and note');
 assert.deepEqual(report.errors,[]);report.status='passed';console.log(JSON.stringify(report));
})().catch(e=>{report.status='failed';report.failure=e.stack;console.error(e);process.exitCode=1;}).finally(async()=>{fs.writeFileSync(path.join(out,'link-browser-results.json'),JSON.stringify(report,null,2));if(browser)await browser.close();proc.kill();fs.rmSync(data,{recursive:true,force:true});});
