const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),assert=require('assert/strict'),{spawn}=require('child_process');
const ROOT=path.resolve(__dirname,'..'),OUT=ROOT+'/qa-artifacts',LIB='/tmp/pqc-scratch/node_modules';fs.mkdirSync(OUT,{recursive:true});
for(const [pkg,file] of [['scratch-vm','scratch-vm.js'],['scratch-render','scratch-render.js'],['scratch-storage','scratch-storage.js']])fs.copyFileSync(LIB+'/'+pkg+'/dist/web/'+file,OUT+'/'+file);
for(let d=15;d<=30;d++)fs.copyFileSync(ROOT+'/public/scratch-day-'+d+'.sb3',OUT+'/scratch-day-'+d+'.sb3');
fs.writeFileSync(OUT+'/scratch-test.html','<!doctype html><html><meta charset="utf-8"><title>Scratch engine lesson verification</title><canvas id="stage" width="480" height="360"></canvas><script src="scratch-storage.js"></script><script src="scratch-render.js"></script><script src="scratch-vm.js"></script><script>window.vm=new window.VirtualMachine();window.renderer=new window.ScratchRender(document.querySelector("canvas"));vm.attachRenderer(renderer);vm.attachStorage(new (window.ScratchStorage.ScratchStorage || window.ScratchStorage.default || window.ScratchStorage)());vm.setTurboMode(false);vm.start();</script>');
const server=spawn('python3',['-m','http.server','8100','--bind','127.0.0.1'],{cwd:OUT,stdio:'ignore'});let browser;const report={status:'running',engine:'Official Scratch VM, renderer and storage in real Chromium',lessons:[],errors:[]};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{await sleep(500);browser=await chromium.launch({args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});const p=await browser.newPage();p.on('pageerror',e=>report.errors.push(e.message));await p.goto('http://127.0.0.1:8100/scratch-test.html');await p.waitForFunction(()=>window.vm?.runtime&&window.renderer);assert.deepEqual(report.errors,[]);
 for(let d=15;d<=30;d++){
  await p.evaluate(async d=>{vm.stopAll();await vm.loadProject(await (await fetch('scratch-day-'+d+'.sb3')).arrayBuffer());vm.greenFlag();},d);await sleep(250);let info={id:'game-'+d,checks:['.sb3 loads in official engine and green flag starts']};report.lessons.push(info);
  let v=await p.evaluate(()=>{const t=vm.runtime.targets.find(t=>t.getName()==='Player');return {x:t.x,y:t.y};});assert.equal(v.x,-150);assert.equal(v.y,0);
  if(d>=16){await p.evaluate(()=>vm.postIOData('keyboard',{key:'ArrowRight',keyCode:39,isDown:true}));await sleep(200);await p.evaluate(()=>vm.postIOData('keyboard',{key:'ArrowRight',keyCode:39,isDown:false}));await sleep(100);const x=await p.evaluate(()=>vm.runtime.targets.find(t=>t.getName()==='Player').x);if(d===16)assert.equal(x,-140);else assert(x>-150);info.checks.push(d===16?'Key event moves 10':'Forever/key condition moves while held');}
  if(d>=18){await p.evaluate(()=>{const player=vm.runtime.targets.find(t=>t.getName()==='Player'),treasure=vm.runtime.targets.find(t=>t.getName()==='Treasure1');player.setXY(treasure.x,treasure.y);});await p.waitForFunction(()=>!vm.runtime.targets.find(t=>t.getName()==='Treasure1').visible);info.checks.push('Actual renderer collision hides pickup');if(d>=19){assert.equal(await p.evaluate(()=>vm.runtime.getTargetForStage().variables.score.value),1);await sleep(150);assert.equal(await p.evaluate(()=>vm.runtime.getTargetForStage().variables.score.value),1);info.checks.push('Exactly one score increment per contact');}}
  if(d>=21){await p.evaluate(()=>{vm.greenFlag();});await sleep(200);await p.evaluate(()=>vm.postIOData('keyboard',{key:'ArrowUp',keyCode:38,isDown:true}));await sleep(150);await p.evaluate(()=>vm.postIOData('keyboard',{key:'ArrowUp',keyCode:38,isDown:false}));assert((await p.evaluate(()=>vm.runtime.targets.find(t=>t.getName()==='Player').y))>0);info.checks.push('All-direction pattern includes working up input');}
  if(d>=22){await p.evaluate(()=>vm.greenFlag());await sleep(200);for(let i=1;i<=5;i++){await p.evaluate(i=>{const player=vm.runtime.targets.find(t=>t.getName()==='Player'),treasure=vm.runtime.targets.find(t=>t.getName()==='Treasure'+i);player.setXY(treasure.x,treasure.y);},i);await p.waitForFunction(i=>!vm.runtime.targets.find(t=>t.getName()==='Treasure'+i).visible,i);}assert.equal(await p.evaluate(()=>vm.runtime.getTargetForStage().variables.score.value),5);info.checks.push('Five sprite pickups produce score 5');}
  if(d>=24){await p.waitForFunction(()=>vm.runtime.getTargetForStage().variables.playing.value===0);info.checks.push('Win broadcast stops playing');}
  if(d>=23){await p.evaluate(()=>vm.greenFlag());await sleep(200);await p.evaluate(()=>{const player=vm.runtime.targets.find(t=>t.getName()==='Player'),hazard=vm.runtime.targets.find(t=>t.getName()==='Hazard');player.setXY(hazard.x,hazard.y);});await p.waitForFunction(()=>vm.runtime.getTargetForStage().variables.playing.value===0);const x=await p.evaluate(()=>vm.runtime.targets.find(t=>t.getName()==='Player').x);await p.evaluate(()=>vm.postIOData('keyboard',{key:'ArrowRight',keyCode:39,isDown:true}));await sleep(150);await p.evaluate(()=>vm.postIOData('keyboard',{key:'ArrowRight',keyCode:39,isDown:false}));assert.equal(await p.evaluate(()=>vm.runtime.targets.find(t=>t.getName()==='Player').x),x);info.checks.push('Hazard Lose broadcast stops movement');}
  if(d>=19){await p.evaluate(()=>vm.greenFlag());await sleep(200);assert.equal(await p.evaluate(()=>vm.runtime.getTargetForStage().variables.score.value),0);assert.equal(await p.evaluate(()=>vm.runtime.targets.find(t=>t.getName()==='Treasure1').visible),true);info.checks.push('Replay resets score and treasure');}
  // Exercise the real VM serialization and reload used by .sb3 saves.
  if(d===15||d>=29){await p.evaluate(async()=>{const blob=await vm.saveProjectSb3();await vm.loadProject(await blob.arrayBuffer());vm.greenFlag();});await sleep(200);assert.equal(await p.evaluate(()=>vm.runtime.targets.find(t=>t.getName()==='Player').x),-150);info.checks.push('Editable .sb3 save and reopen round trip');}
  if([18,24,30].includes(d))await p.screenshot({path:OUT+'/scratch-'+d+'.png'});info.status='technical-pattern-passed';console.log('PASS Scratch game-'+d);
 }
 assert.deepEqual(report.errors,[]);report.status='passed';
})().catch(e=>{report.status='failed';report.failure=e.stack;console.error(e);process.exitCode=1;}).finally(async()=>{fs.writeFileSync(OUT+'/scratch-results.json',JSON.stringify(report,null,2));await browser?.close();server.kill();for(const name of ['scratch-storage.js','scratch-render.js','scratch-vm.js'])fs.rmSync(OUT+'/'+name,{force:true});});
