const fs=require('fs'),vm=require('vm'),assert=require('assert'),path=require('path');const root=path.join(__dirname,'..');let clock=0;
const ctx=new Proxy({measureText:s=>({width:s.length*9})},{get:(o,k)=>o[k]||(()=>{})});const env={window:{},Image:class{constructor(){this.complete=true;this.naturalWidth=1536;}addEventListener(){}removeEventListener(){}},performance:{now:()=>clock},requestAnimationFrame:fn=>setImmediate(()=>fn(clock+=80)),setTimeout:fn=>setImmediate(()=>{clock+=80;fn();}),console};vm.createContext(env);vm.runInContext(fs.readFileSync(root+'/public/engine.js','utf8'),env);const P=env.window.PQC,DATA=JSON.parse(fs.readFileSync(root+'/public/curriculum.json'));
function fresh(){const p=P.defaultProject(),reports=[];const s=new P.Stage({getContext:()=>ctx,addEventListener(){},getBoundingClientRect:()=>({left:0,top:0,width:800,height:450})},p,r=>reports.push(r));s.delay=async()=>{};p.sound=false;return {p,s,reports};}
(async()=>{
 for(const theme of Object.keys(P.THEMES))for(const l of DATA.lessons){const {p,s}=fresh();p.theme=theme;p.scenes[0].program=l.starter;assert(P.validateProject(p));await s.run();s.destroy();}
 let {p,s,reports}=fresh();p.scenes[0].trigger='tap';p.scenes[0].program=[{op:'hide',value:0,target:2}];await s.run();s.pointer({clientX:110,clientY:345});await new Promise(setImmediate);assert(!s.runtime.players[1].visible);assert(!s.armed);assert(!s.running);
 ({p,s,reports}=fresh());p.scenes[0].trigger='controls';p.scenes[0].program=[];await s.run();const before=reports.length;const movement=s.control('right');s.stop();await movement;assert.equal(reports.length,before);s.destroy();
 ({p,s,reports}=fresh());p.scenes[0].program=[{op:'message',value:0,target:1}];p.scenes[1].trigger='message';p.scenes[1].program=[{op:'say',value:'Reply',target:2}];await s.run();assert.equal(p.scene,1);assert.equal(s.runtime.players[1].speech,'Reply');
 ({p,s,reports}=fresh());for(const scene of p.scenes)scene.program=[{op:'next',value:0,target:1}];await s.run();assert(reports.some(r=>r.error&&r.text.includes('Too many scene changes')));assert(!s.running);
 ({p,s,reports}=fresh());s.layout='treasure';for(let i=0;i<30;i++)s.pointer({clientX:400,clientY:200});assert.equal(p.scenes[0].items.length,20);s.layout='hazard';for(let i=0;i<15;i++)s.pointer({clientX:400,clientY:200});assert.equal(p.scenes[0].hazards.length,10);s.layout='erase';s.pointer({clientX:400,clientY:200});assert.equal(p.scenes[0].items.length,3);assert.equal(p.scenes[0].hazards.length,0);s.layout='player1';s.pointer({clientX:-1000,clientY:1000});assert.equal(p.scenes[0].players[0].x,35);assert.equal(p.scenes[0].players[0].y,410);
 for(let avatar=0;avatar<30;avatar++){p.scenes[0].players[0].avatar=avatar;assert(P.validateProject(p));}
 console.log('Engine edges: 270 starter/theme executions, tap rearming, canceled controls, message routing, scene-loop guard, layout caps/erase/bounds and all 30 avatars passed in simulated canvas.');
})().catch(e=>{console.error(e);process.exitCode=1;});
