"""Authored lesson examples and activity guidance; used by make_curriculum.py."""
def b(op,value=0,target=1,**kw):return dict(op=op,value=value,target=target,**kw)
def scene(program,trigger='start',items=None):
 return dict(trigger=trigger,program=program,code='',players=[dict(x=110,y=345,avatar=None),dict(x=650,y=345,avatar=None)],items=items if items is not None else [dict(x=x,y=345) for x in (230,350,470)],hazards=[])
def code(blocks):
 lines=[]
 for x in blocks:
  op=x['op'];v=x['value']
  if op in ('right','left','up','down'):lines.append(f'move {op} {v}')
  elif op=='repeat':lines.append(f"repeat {x['count']} {x['direction']} {v}")
  elif op in ('say','ifwin'):lines.append(f'{op} "{v}"')
  elif op=='wait':lines.append(f'wait {v}')
  else:lines.append(op)
 return '\n'.join(lines)
STORY={
1:[b('right',1)],2:[b('right',2)],3:[b('right',2),b('say','Hello')],4:[b('up',1),b('down',2)],5:[b('say','Ready'),b('right',2)],6:[b('say','Hello'),b('wait',1),b('say','Goodbye')],7:[b('right',1),b('say','My story'),b('wait',1)],8:[b('repeat',1,count=3,direction='right')],9:[b('repeat',1,count=2,direction='up')],10:[b('say','Welcome to my adventure!')],11:[b('say','Hello',2),b('say','Hello back!',1)],12:[b('say','You tapped me!')],13:[b('say','Hello'),b('sound')],14:[b('say','Goodbye'),b('wait',1),b('say','Hello')],15:[b('say','Welcome to Scene 1')],16:[b('say','Welcome'),b('next')],17:[b('say','Are you there?'),b('message')],18:[b('hide',target=2),b('wait',1),b('show',target=2)],19:[b('say','Press Run to begin!')],20:[b('say','I am looking for my friend'),b('right',1),b('wait',1)],21:[b('say','Hello, friend!'),b('right',1)],22:[b('repeat',1,count=2,direction='right'),b('wait',1),b('say','I found you!',2)],23:[b('say','We made it!'),b('next')],24:[b('hide',target=2),b('wait',1),b('show',target=2),b('say','Surprise!',2)],25:[b('say','A short line'),b('wait',1),b('say','The end')],26:[b('say','My favorite story'),b('right',1)],27:[b('say','Press Run; watch my adventure'),b('right',1)],28:[b('say','A clearer beginning'),b('wait',1),b('say','The end')],29:[b('say','My saved story'),b('next')],30:[b('repeat',1,count=2,direction='right'),b('say','Our adventure'),b('next')]}
GAME={1:[b('right',2)],2:[b('right',2),b('up',1)],3:[b('say','Started!')],4:[b('right',6)],5:[b('right',2)],6:[b('right',2),b('ifwin','You win')],7:[b('right',6),b('ifwin','You win')],8:[b('repeat',1,count=3,direction='right')],9:[b('right',6)],10:[],11:[],12:[],13:[b('say','Collect three treasures. Use the direction buttons.')],14:[]}
DEV={1:[b('right',2)],2:[b('right',4)],3:[b('right',1),b('say','Hello')],4:[b('right',2),b('ifwin','You win')],5:[b('repeat',1,count=3,direction='right')],6:[b('right',2)],7:[b('repeat',2,count=3,direction='right'),b('ifwin','You win')]}
EXPECTED_STORY={1:'Companion 1 moves right by one step (60 stage units).',2:'4 moves farther than 2, unless the character reaches an edge.',3:'Movement happens before the greeting.',4:'The character finishes one step lower than it began.',5:'The greeting happens before movement in one version and after it in the other.',6:'The greeting stays visible for one second before Goodbye.',7:'A move, speech and wait sequence runs in the order you chose.',8:'A repeat with count 3 ends in the same place as three one-step moves.',9:'Count 3 moves one step farther up than count 2.',10:'Only the speech text changes; the character stays in the same place.',11:'Companion 2 greets and Companion 1 answers.',12:'Nothing runs until you press Run and tap Companion 1.',13:'The greeting and movement still work when sound is off.',14:'Hello comes before Goodbye after you fix the order.',15:'Both scenes keep separate programs; the theme belongs to the whole project.',16:'Next scene changes to Scene 2 and runs its program.',17:'Send message runs Scene 2 only when its trigger is Message arrives.',18:'Companion 2 is hidden during the wait, then appears.',19:'Reset followed by Run repeats the same clear beginning.',20:'Your three actions match the beginning you planned.',21:'Your greeting and movement introduce the character.',22:'A repeat, wait or second-character action adds a middle.',23:'The entire story reaches a clear ending.',24:'Run arms the tap event; tapping Companion 1 reveals the other character.',25:'Each short line remains visible long enough to read; sound is optional.',26:'One small improvement works in your existing story.',27:'A test player can begin and you record one confusing part.',28:'Your chosen fix works when you replay the entire story.',29:'A downloaded project reopens with the same title, scenes and commands.',30:'Both scenes work; you can explain the repeat and event and change one command.'}
EXPECTED_GAME={1:'The character moves right two steps.',2:'Right changes x; up decreases the stage y position.',3:'Start runs immediately; tap waits for Run and a character tap.',4:'Each of the three treasures increases score once; Reset returns score to zero.',5:'The score changes when the moving character touches the placed treasure.',6:'The condition stays silent below target and speaks after reaching target.',7:'An original route collects three treasures and says a win message.',8:'Three single moves and a repeat with count 3 end at the same place.',9:'Speed changes elapsed movement time, not final distance.',10:'Direction buttons and arrow keys move the player after Run.',11:'Touching a hazard ends the round; a different route can avoid it.',12:'Winning displays the goal; Reset restores score and all treasures.',13:'The player can read your goal and play your small layout.',14:'You observe a missed pickup, a loss, a win and a successful restart.'}
EXPECTED_DEV={1:'Changing the number changes movement distance.',2:'Speed 6 reaches the same point sooner than speed 3; a GDScript variable names a value.',3:'The same sequence works twice; the GDScript function has an indented body.',4:'ifwin speaks only after score meets the target.',5:'Repeat produces the same endpoint as three moves; the GDScript loop runs three times.',6:'The typo produces a line-numbered error; corrected code moves the character.',7:'Your typed repeat collects three treasures and the condition announces the win.'}
NOTES={('story',1):'Character choices are inside Scene settings. Pick Companion 1 there.',('story',4):'Clear commands first. One step is 60 stage units; the bottom edge is y=410, so use this short route.',('story',11):'The Character for command selector is on each block. Typed mode controls only Companion 1.',('story',12):'Use Start when → Character is tapped. You must press Run again before a second tap sequence.',('story',15):'Scene 2 is selected above the editor. Give it its own greeting. A theme change applies to the entire project, not just one scene.',('story',16):'Give Scene 2 a Say ending and Start when → Run is pressed. Return to Scene 1 before Run.',('story',17):'In Scene 2 add Say "Hello back!" and set Start when → Message arrives. Return to Scene 1, set Run is pressed, then add Send message.',('story',23):'Before using Next scene, give Scene 2 an ending and the Run is pressed trigger. Start the full story from Scene 1.',('story',24):'Tap events listen to Companion 1. Show Companion 2 can be the response. Press Run to arm it each time.',('story',26):'Keep your story project: opening another day does not create a new project. Choose a favorite unfinished task.',('story',29):'Download project saves a .pqc.json file. Open project restores it. Try the reopened version; the website does not save Scratch/Godot files.',('story',30):'Scene 1 can use a repeat then Next scene; Scene 2 can say The end. Both should use Run is pressed for this example.',('game',4):'The practice stage already contains three treasures. Do not add three more. Use Erase to remove extras, then place exactly three. Set target in Scene settings.',('game',5):'For a controlled test remove existing treasures and place one at x≈230 on the same ground line as Companion 1. Switch Arrange the stage back to Play mode.',('game',6):'Use one treasure and target 1 for the first test. Move right 2 before the condition. For the false test move up 1 instead. A condition checks at its own place in the sequence.',('game',10):'Use Start when → Direction controls. An empty program is fine. Run enables the direction pad and arrow keys.',('game',11):'Use Arrange the stage → Hazard and tap on the ground to place it. Choose Play mode, then Run. Reset before testing a safer route.',('game',12):'Reset restarts the current scene. Choose Scene 1 before Run. On a loss or win press Reset and Run to begin again.',('dev',4):'Use target 1, one treasure on the ground at x≈230, move right 2, then ifwin "You win". Compare move up 1 before the condition.',('dev',6):'Try moove right 2, then correct it to move right 2. The lesson example contains the corrected version.'}
BEFORE_STORY={1:'Choose Scene 1 and Picture blocks. Start with an empty program; use Clear commands if needed.',2:'Keep one Move right block from Quest 1. If you start here, add Move right 1 first.',3:'For this practice, choose Scene 1, Run is pressed, and Clear commands before adding the two actions.',4:'Choose Scene 1, Run is pressed, and Clear commands before building the up/down sequence.',5:'Clear the practice commands first, then build the two actions in today’s steps.',6:'Clear the practice commands first, then build Hello, Wait and Goodbye.',7:'Use Clear commands for this independent practice; keep your stage layout.',8:'Clear the practice commands first. Add a Repeat move block, set right, amount 1 and count 3.',9:'Clear the practice commands first. Add Repeat move with up, amount 1 and count 2.',10:'Use a single Say block for this practice. Keep Scene 1 and Run is pressed.',11:'Clear the practice commands, then add the two greeting blocks and choose each companion.',12:'Keep a greeting program. Select Character is tapped, press Run, then tap Companion 1.',13:'Clear the practice commands, add a greeting, then Play sound. Keep Run is pressed.',14:'Clear the practice commands, then deliberately build the mixed-up greeting sequence.',15:'Keep Scene 1. Select Scene 2 above the editor and give it a new greeting; themes apply to both scenes.',16:'Give Scene 2 an ending with Run is pressed. Return to Scene 1 and clear its practice commands.',17:'Give Scene 2 a Say reply and Message arrives trigger. Return to Scene 1, choose Run is pressed and clear its practice commands.',18:'Choose Scene 1 and Run is pressed. Clear its practice commands before the hide/wait/show sequence.',19:'Choose Scene 1 and Run is pressed. Clear the practice commands and write a new welcome.'}
BEFORE_GAME={1:'Choose Scene 1 and Picture blocks; clear practice commands before adding movement.',2:'Choose Scene 1 and Run is pressed. Clear commands before the right/up sequence.',3:'Keep a short movement or greeting program; compare Run is pressed with Character is tapped.',4:'Choose Scene 1 and Run is pressed. Clear commands and use exactly three treasures on the ground.',5:'Clear commands. Erase extra treasures so you can test one treasure at a time; use Run is pressed.',6:'Use the walkthrough’s one-treasure setup and target 1. Movement must come before the score condition.',7:'Download a backup if needed; make your own three-treasure layout with a reachable route.',8:'Clear practice commands before comparing three moves with one repeat.',9:'Use one long Move right block, amount 6, so speed comparisons have the same distance.',10:'Choose Direction controls. You can clear the program; Run enables the direction buttons.',11:'Keep Direction controls; place one hazard, switch Arrange the stage back to Play mode, then Run.',12:'Use Direction controls and a reachable treasure target. Reset and Run start another round.',13:'Keep your layout. Add Say instructions under Direction controls so they appear when Run is pressed.',14:'Keep your game layout and test it in Direction controls. Write down any confusing rule.'}
BEFORE_DEV={1:'Open Type commands and type move right 2 on an empty line.',2:'First type speed 3 and move right 4 on separate lines. Then change only 3 to 6.',3:'Clear the typed practice code. Write a move and a say line; the GDScript comparison below is separate.',4:'Use one treasure on the ground, target 1, then move right 2 followed by ifwin "You win". Compare a route that misses it.',5:'Clear the typed practice code before comparing the repeat with three separate moves.',6:'First type move right 2. Misspell move, run it, then correct it.',7:'Use exactly three reachable treasures and target 3. Plan your own route; the practice setup is available if you start here.'}
REFS={2:'extends Node\nvar speed: float = 3.0\n\nfunc _ready():\n    speed = 6.0\n    print(speed)',3:'extends Node\n\nfunc greet():\n    print("Hello!")\n\n# Call greet() from _ready() to run it.\nfunc _ready():\n    greet()\n    greet()',5:'extends Node\n\nfunc _ready():\n    for step in range(3):\n        print(step)\n# This prints 0, 1, 2.'}
def enrich(l):
 path,day=l['path'],l['day'];l['success']=l['recall'];l['walkthrough']=[]
 if l['mode']=='browser':
  l['before']={'story':BEFORE_STORY,'game':BEFORE_GAME,'dev':BEFORE_DEV}[path].get(day,'Continue your own story project. Save a backup before a large change; do not replace it with a practice stage.')
  programs={'story':STORY,'game':GAME,'dev':DEV};l['starter']=programs[path][day];l['starterCode']=code(l['starter']);l['success']={'story':EXPECTED_STORY,'game':EXPECTED_GAME,'dev':EXPECTED_DEV}[path][day]
  s1=scene(l['starter']);s2=scene([b('say','The end!')],items=[])
  target=3;speed=3
  if (path=='story' and day in (12,24)):s1['trigger']='tap'
  if path=='story' and day==17:s2['trigger']='message';s2['program']=[b('say','Hello back!',2)]
  if path=='game' and day>=10:s1['trigger']='controls'
  if path=='game' and day in (5,6):s1['items']=[dict(x=230,y=345)];target=1
  if path=='game' and day in (11,13,14):s1['hazards']=[dict(x=290,y=345)]
  if path=='dev' and day==4:s1['items']=[dict(x=230,y=345)];target=1
  if path=='dev' and day==2:l['starterCode']='speed 3\nmove right 4'
  for s in (s1,s2):s['code']=code(s['program'])
  if path=='dev':s1['code']=l['starterCode']
  l['practice']=dict(schema=1,title=f"Practice: {l['title']}"[:80],theme='royal',mode='code' if path=='dev' else 'blocks',target=target,speed=speed,sound=True,scene=0,scenes=[s1,s2])
  l['walkthrough']=[NOTES.get((path,day),'Start from Scene 1. Keep Picture blocks for this activity.' if path!='dev' else 'Use Type commands. These teaching commands are not GDScript.'),'Follow the three quest steps above. Try the example only if you need a hint; change one thing and compare.','The example button changes commands only. Load practice stage also restores the example layout and triggers; download your creation before replacing it.']
  if path=='dev' and day in REFS:l['reference']=REFS[day]
 return l
